---
- name: make direcotry
  hosts: all
  tasks:
  
  - name: make direcotry
    file:
      path: "/home/tzahi/.ssh"
      state: directory

  - name: create empty file
    file:
      path: "/home/tzahi/.ssh/authorized_keys"
      state: touch

  - name: Copy file with owner and permissions
    copy:
      src: /home/tzahi/awx/id_ed25519.pub
      dest: /home/tzahi/.ssh/
      owner: tzahi
      group: tzahi
      mode: '0600'

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: tzahi
      state: present
      key: "{{ lookup('file', '/home/tzahi/.ssh/id_ed25519.pub') }}"
