---
- name: Playbook to pull an portainer Image For Docker
  hosts: all
  tasks:

  - name: Create a portainer Container
    shell: docker run -d -p 8000:8000 --name portainer_server portainer/portainer

  - name: start a portainer Container
    shell: docker container start portainer_server
