---
- name: Playbook for Install Multiple the packages
  hosts: all
  become: true
  tasks:
  
  - name: Install a list of packages
    apt:
      pkg:
      - software-properties-common
      - ansible
      - packer
      - vault
      - terraform
