---
- name: PlayBook To Install Docker
  hosts: all
  tasks:
  
  - name: Install all the packages
    apt: name={{ item }} 
    state: installed
    update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - docker.io
      - python3-pip
      - python-setuptools
