---
- name: Playbook for Install Multiple the packages
  hosts: all
  tasks:
  
  - name: Install all the packages
    apt: name={{ item }} 
    state: installed
    update_cache: yes
    with_items:
       - software-properties-common
       - ansible
       - packer
       - vault
       - terraform
