---
- name: PlayBook To Install Docker
  hosts: all
  tasks:
  
  - name: Install a list of packages
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - docker.io
      - python3-pip

  - name: Install Docker Module for Python
    pip:
      name: 
      - awscli
      - docker
