---
- name: Installing Puppet Agent Service Playbook
  hosts: all
  become: true
  tasks:

  - name: Download puppet deb File
    get_url:
      url: https://apt.puppetlabs.com/puppet7-release-focal.deb
      dest: /tmp/
      mode: '0744'
    
  - name: Installing The puppet7-release-focal.deb File
    apt:
      deb: /tmp/puppet7-release-focal.deb

  - name: Update apt and install puppet-agent
    apt: 
      update_cache: yes 
      name: puppet-agent
      state: latest

  - name: Create File puppet.conf
    file:
      path: /etc/puppetlabs/puppet/puppet.conf
      state: touch

  - name: Update hosts File
    lineinfile:
      path: /etc/hosts
      state: present
      line: '192.168.50.96 puppet puppet.localdomain'
      
  - name: Update puppet.conf File
    lineinfile:
      path: /etc/puppetlabs/puppet/puppet.conf
      state: present
      line: "{{ item }}"
    with_items:
    - '[main]'
    - 'certname = ops03'
    - 'server = puppet'
    
  - name: Starting The puppet Agent Service
    systemd:
      name: puppet
      state: started
      enabled: yes

  - name: Execute a command to Register Puppet Service
    become: true
    shell: sudo /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true

  - name: Wait for 10 seconds to the Puppet Service to be Ready
    wait_for:
      timeout: 10

  - name: Execute a command to Register Puppet Agent to the Server
    become: true
    shell: /opt/puppetlabs/bin/puppet agent -t
    
