---
- name: Ansible Playbook Add Repository
  hosts: all
  tasks:

  - name: Add Hashicorp's official GPG key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
        
  - name: Add Repository into Sources List and apt-get update
    apt_repository:
      repo: deb https://apt.releases.hashicorp.com focal main
      state: present
           
  - name: Installing software-properties-common Package
    apt:
      name: software-properties-common
      state: present
      update_cache: yes
