---
- name: Ansible Playbook Add Repository
  hosts: all
  become: true
  tasks:

  - name: Add Hashicorp's official GPG key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
        
  - name: Add Repository into Sources List and Run apt-get update
    apt_repository:
      repo: deb https://apt.releases.hashicorp.com focal main
      state: present
      update_cache: yes
      
  - name: Add Ansible stable repository from PPA and install its signing key on Ubuntu target
    apt_repository:
      repo: ppa:ansible/ansible
      state: present
      update_cache: yes
      
  - name: Installing software-properties-common Package
    apt:
      name: software-properties-common
      state: present
      update_cache: yes
