---
- name: PlayBook To Install Ansible Server on Ubuntu 
  hosts: all
  tasks:

  - name: Installing software-properties-common Package
    apt:
      name: software-properties-common
      state: present
      update_cache: yes
        
  - name: Add Ansible stable repository from PPA and install its signing key on Ubuntu target
    apt_repository:
      repo: ppa:ansible/ansible
      
