---
- name: Ansible Playbook Add Repository
  hosts: all
  tasks:

  - name: Add Hashicorp's official GPG key
    shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
     state: present
        
  - name: Add Specified Repository into Sources List and Run apt-get update
    apt_repository:
      repo:  "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      state: present
      update_cache: yes
      
  - name: Add Ansible stable repository from PPA and install its signing key on Ubuntu target
    apt_repository:
      repo: ppa:ansible/ansible
      state: present
      update_cache: yes
      
  - name: Installing software-properties-common Package
    apt:
      name: software-properties-common
      state: present
      update_cache: yes
